<a href="https://colab.research.google.com/github/mihirmaurya31/XAI-for-Phishing-URL-detection/blob/main/phish_url.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Installations of Libraries**

In [ ]:
!pip install tldextract
!pip install python-whois publicsuffix2 python-dateutil

Collecting tldextract
  Downloading tldextract-5.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from tldextract) (3.10)
Requirement already satisfied: requests>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from tldextract) (2.32.4)
Collecting requests-file>=1.4 (from tldextract)
  Downloading requests_file-2.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.12/dist-packages (from tldextract) (3.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.1.0->tldextract) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.1.0->tldextract) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.1.0->tldextract) (2025.10.5)
Downloading tldextract-5.3.0-py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.4/107.4 kB 3.1 MB/s eta 0:00:00
Downloading requests_file-2.1.0-py2.py3-none-any.whl (4.2 kB)
Installing collected packages: requests-file, tldextract
Successfully installed requests-file-2.1.0 tldextract-5.3.0
Collecting python-whois
  Downloading python_whois-0.9.6-py3-none-any.whl.metadata (3.0 kB)
Collecting publicsuffix2
  Downloading publicsuffix2-2.20191221-py2.py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil) (1.17.0)
Downloading python_whois-0.9.6-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 3.8 MB/s eta 0:00:00
Downloading publicsuffix2-2.20191221-py2.py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.0/89.0 kB 7.0 MB/s eta 0:00:00
Installing collected packages: publicsuffix2, python-whois
Successfully installed publicsuffix2-2.20191221 python-whois-0.9.6

***Base Dataset***

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv("phishing_site_urls.csv")

# Inspect structure
print(df.head())
print(df['Label'].value_counts())

# Map labels: bad -> 1 (phishing), good -> 0 (legit)
df['Label'] = df['Label'].map({'bad': 1, 'good': 0})

# Drop duplicates if any
df = df.drop_duplicates()

# Reset index
df = df.reset_index(drop=True)

print("Dataset shape after cleaning:", df.shape)
print(df.head())

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad
Label
good    392924
bad     156422
Name: count, dtype: int64
Dataset shape after cleaning: (507210, 2)
                                                 URL  Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...    1.0
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...    1.0
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....    1.0
3  mail.printakid.com/www.online.americanexpress....    1.0
4  thewhiskeydregs.com/wp-content/themes/widescre...    1.0

**Adding Benign Urls from Tranco**

In [ ]:
import pandas as pd

# Load Tranco file (no header)
tranco_df = pd.read_csv("tranco_7NZNX.csv", header=None, names=["Rank", "Domain"])

# Create full URLs by prefixing http:// (or https://)
tranco_df["URL"] = "http://" + tranco_df["Domain"]

# Assign label = 0 (benign)
tranco_df["Label"] = 0

# Keep only relevant columns
benign_df = tranco_df[["URL", "Label"]]

print(benign_df.head())
print("Total benign samples:", benign_df.shape[0])

                     URL  Label
0      http://google.com      0
1         http://mail.ru      0
2   http://microsoft.com      0
3    http://facebook.com      0
4  http://googleapis.com      0
Total benign samples: 1000000

**Attributes based on URL**

**Building dataset based on Algorithm 1**
Algorithm 1 Feature extraction process

Input: URLs  Array of URLs.

Input: signs  Array of signs to count.

Output: dataset.csv  Output csv document.

1: i ← 0

2: totalURLs ← lenght(URLs)  Get the number of URLs in array.

3: while i < totalURLs do

4: url ← URLs(i)

5: countsUrl ← getCounts(url, signs)  Get signs and character counts.

6: for substring in splitURL(url) do  Iterate through the sub-strings of URL.

7: countsSubstring ← getCounts(substrings, signs)  Get signs and character counts.

8: end for

9: measuredFeatures ← f etchFeatures(url)  Get features from external services.

10: toCsv(countsUrl, countsSubstring, measuredFeatures)  Append row to csv.

11: i ← i + 1

12: end while

In [ ]:
# === FINAL: Algorithm 1 Full Dataset Feature Extraction ===
import time, concurrent.futures, requests, pandas as pd, re
from urllib.parse import urlparse, urlunparse, quote
from requests.utils import requote_uri

# -----------------------------
# Config
# -----------------------------
CONNECTIONS = 100             # parallel workers
HTTP_CONNECT_TIMEOUT = 2.0    # seconds to connect
HTTP_READ_TIMEOUT = 2.0       # seconds to read
TIMEOUT = (HTTP_CONNECT_TIMEOUT, HTTP_READ_TIMEOUT)
UA = {"User-Agent": "Mozilla/5.0 (compatible; MScFeatureExtractor/1.0)"}
OUTPUT_FILE = "dataset_full.csv"

SIGNS = [".","-","_","/","?","=","@","&","!"," ","~","˜",",","+","*","#","$","%"]
SIGN_LABELS = {
    ".":"dot","-":"hyphen","_":"underline","/":"slash","?":"questionmark","=":"equal",
    "@":"at","&":"and","!":"exclamation"," ":"space","~":"tilde","˜":"tilde",",":"comma",
    "+":"plus","*":"asterisk","#":"hashtag","$":"dollar","%":"percent"
}

# -----------------------------
# Helpers
# -----------------------------
def normalize_url(u: str) -> str:
    s = (str(u) or "").strip()
    if not s: return ""
    if s.startswith("//"): s = "http:" + s
    if "://" not in s: s = "http://" + s
    p = urlparse(s)
    if not p.netloc and p.path:
        p = urlparse(f"{p.scheme}://{p.path}")
    host = p.hostname or ""
    port = p.port
    user = p.username or ""
    pwd  = p.password or ""
    userinfo = ""
    if user:
        userinfo = quote(user, safe="")
        if pwd: userinfo += ":" + quote(pwd, safe="")
        userinfo += "@"
    if ":" in host and not (host.startswith("[") and host.endswith("]")):
        host = f"[{host}]"
    netloc = userinfo + host + (f":{port}" if port else "")
    return requote_uri(urlunparse((p.scheme, netloc, p.path or "", p.params or "", p.query or "", p.fragment or "")))

def splitURL(url: str) -> dict:
    try:
        p = urlparse(normalize_url(url))
        directory = p.path or ""
        return {
            "domain":   p.hostname or "",
            "directory": directory,
            "file":      directory.split("/")[-1] if directory else "",
            "params":    p.query or "",
            "fragment":  p.fragment or "",
        }
    except Exception:
        return {"domain":"","directory":"","file":"","params":"","fragment":""}

def getCounts(text: str, signs: list, scope: str) -> dict:
    s = text if isinstance(text, str) else ""
    out = {}
    tilde_total, done = s.count("~") + s.count("˜"), False
    for ch in signs:
        token = SIGN_LABELS.get(ch, f"u{ord(ch)}"); col = f"qty_{token}_{scope}"
        if ch in ("~","˜"):
            if not done:
                out[col] = tilde_total; done = True
        else:
            out[col] = s.count(ch)
    if scope == "url": out["length_url"] = len(s)
    else: out[f"{scope}_length"] = len(s)
    return out

# -----------------------------
# Parallel HTTP HEAD (Jack’s fast approach)
# -----------------------------
def _head_worker(url: str) -> dict:
    res = {
        "time_response": float("nan"),
        "qty_redirects": 0,
        "http_status": float("nan"),
        "server_header": "",
        "tls_ssl_certificate": 1 if normalize_url(url).lower().startswith("https") else 0,
    }
    try:
        t0 = time.perf_counter()
        r = requests.head(normalize_url(url), headers=UA, timeout=TIMEOUT, allow_redirects=True)
        res["time_response"] = int((time.perf_counter() - t0) * 1000)
        res["qty_redirects"] = len(r.history)
        res["http_status"]   = r.status_code
        res["server_header"] = r.headers.get("Server","")
    except requests.exceptions.Timeout:
        pass
    except Exception:
        pass
    return res

def fetch_features_parallel(urls, max_workers=CONNECTIONS):
    out = [None] * len(urls)
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(_head_worker, u): idx for idx, u in enumerate(urls)}
        done = 0; total = len(urls); step = max(1, total // 10)
        for fut in concurrent.futures.as_completed(futures):
            idx = futures[fut]
            try:
                out[idx] = fut.result()
            except Exception:
                out[idx] = _head_worker("")
            done += 1
            if done % step == 0 or done == total:
                print(f"  HEAD progress: {done}/{total}")
    return out

# -----------------------------
# Algorithm 1 Runner (full dataset)
# -----------------------------
def run_full_algorithm(input_csv="phishing_site_urls.csv", url_col=None, output_csv=OUTPUT_FILE):
    df = pd.read_csv(input_csv)

    # detect URL column
    if url_col is None:
        for c in ["URL","url","Url","Domain","domain"]:
            if c in df.columns:
                url_col = c; break
        if url_col is None:
            raise ValueError("No URL column found.")

    # Label mapping
    if "Label" in df.columns:
        df["Label"] = df["Label"].map({"bad":1,"good":0}).fillna(df["Label"])

    urls = df[url_col].astype(str).tolist()
    total = len(urls)
    print(f"\n Running Algorithm 1 on full dataset ({total} URLs)...")

    # Step 9 (external): parallel HEADs
    head_feats = fetch_features_parallel(urls, max_workers=CONNECTIONS)

    # Steps 5–8 (URL + substrings)
    rows = []
    i = 0
    while i < total:
        url = urls[i]
        row = {"url": url}
        if "Label" in df.columns:
            row["Label"] = df.loc[i, "Label"]

        # full URL counts
        row.update(getCounts(url, SIGNS, "url"))
        # split and count parts
        for scope, sub in splitURL(url).items():
            row.update(getCounts(sub, SIGNS, scope))
        # cached HEAD results
        row.update(head_feats[i] if head_feats[i] else _head_worker(""))

        rows.append(row)
        if i % max(1, total // 10) == 0 or i == total - 1:
            print(f"  Progress: {i+1}/{total}")
        i += 1

    out_df = pd.DataFrame(rows)
    out_df.to_csv(output_csv, index=False)
    print(f"\n Extracted {total} URLs → {output_csv}")
    display(out_df.head(100))
    return out_df

# -----------------------------
# Run for entire dataset
# -----------------------------
df_full = run_full_algorithm("phishing_site_urls.csv", output_csv="dataset_full.csv")

/tmp/ipython-input-1296916982.py:133: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Label"] = df["Label"].map({"bad":1,"good":0}).fillna(df["Label"])

🚀 Running Algorithm 1 on full dataset (549360 URLs)...
  HEAD progress: 54936/549360

WARNING:urllib3.connection:Failed to parse headers (url=http://www.ccsoftware.ca:80/mdaemon): [MissingHeaderBodySeparatorDefect()], unparsed data: 'last modified header response: If-Modified-Since\r\nX-XSS-Protection: mode=block\r\nDate: Wed, 15 Oct 2025 10:26:49 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'last modified header response: If-Modified-Since\r\nX-XSS-Protection: mode=block\r\nDate: Wed, 15 Oct 2025 10:26:49 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://www.ccsoftware.ca:80/mdaemon/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'last modified header response: If-Modified-Since\r\nX-XSS-Protection: mode=block\r\nDate: Wed, 15 Oct 2025 10:26:49 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'last modified header response: If-Modified-Since\r\nX-XSS-Protection: mode=block\r\nDate: Wed, 15 Oct 2025 10:26:49 GMT\r\n\r\n'

  HEAD progress: 109872/549360
  HEAD progress: 164808/549360
  HEAD progress: 219744/549360
  HEAD progress: 274680/549360
  HEAD progress: 329616/549360

WARNING:urllib3.connection:Failed to parse headers (url=https://www.laurentianbank.ca:443/en): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'

  HEAD progress: 384552/549360

WARNING:urllib3.connection:Failed to parse headers (url=http://scriptperfection.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'powered by: STFU.net\r\nX-Powered-By: ASP.NET\r\nDate: Wed, 15 Oct 2025 11:31:00 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'powered by: STFU.net\r\nX-Powered-By: ASP.NET\r\nDate: Wed, 15 Oct 2025 11:31:00 GMT\r\n\r\n'

  HEAD progress: 439488/549360

WARNING:urllib3.connection:Failed to parse headers (url=https://www.banquelaurentienne.ca:443/en/personal_banking_services/my_money/lbcdirect_electronic_banking_services.html): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.banquelaurentienne.ca:443/en/personal_banking_services/my_futur/indexed_investments.html): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'

  HEAD progress: 494424/549360
  HEAD progress: 549360/549360
  Progress: 1/549360
  Progress: 54937/549360
  Progress: 109873/549360
  Progress: 164809/549360
  Progress: 219745/549360
  Progress: 274681/549360
  Progress: 329617/549360
  Progress: 384553/549360
  Progress: 439489/549360
  Progress: 494425/549360
  Progress: 549360/549360

 Extracted 549360 URLs → dataset_full.csv

,url,Label,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,...,qty_asterisk_fragment,qty_hashtag_fragment,qty_dollar_fragment,qty_percent_fragment,fragment_length,time_response,qty_redirects,http_status,server_header,tls_ssl_certificate
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,1.0,6,4,4,10,1,4,0,3,...,0,0,0,0,0,NaN,0,NaN,,0
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,1.0,5,2,1,4,0,2,0,1,...,0,0,0,0,0,NaN,0,NaN,,0
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,1.0,7,1,0,11,0,0,0,0,...,0,0,0,0,0,NaN,0,NaN,,0
3,mail.printakid.com/www.online.americanexpress....,1.0,6,0,0,2,0,0,0,0,...,0,0,0,0,0,NaN,0,NaN,,0
4,thewhiskeydregs.com/wp-content/themes/widescre...,1.0,1,1,0,10,1,0,0,0,...,0,0,0,0,0,NaN,0,NaN,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,rsaxena.5gbfree.com/facebook.html,1.0,3,0,0,1,0,0,0,0,...,0,0,0,0,0,NaN,0,NaN,,0
96,steamcommunity-giveaway.my3gb.com,1.0,2,1,0,0,0,0,0,0,...,0,0,0,0,0,158.0,0,200.0,,0
97,steamglfts.h16.ru,1.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,NaN,0,NaN,,0
98,steamglfts.hut2.ru/,1.0,2,0,0,1,0,0,0,0,...,0,0,0,0,0,1236.0,1,200.0,nginx/1.24.0 (Ubuntu),0
99,vinzajah.5gbfree.com/login.php,1.0,3,0,0,1,0,0,0,0,...,0,0,0,0,0,NaN,0,NaN,,0

Warning: Total number of columns (115) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
from google.colab import files
files.download("dataset_full.csv")
#------Dataset for Phishing URL-----#

In [ ]:
# ----------------My RAM crashed here so I used C# to extract the features------------------------

# === Algorithm 1 for TRANCO dataset (parallel HTTP + CSV output) ===
'''import time, concurrent.futures, requests, pandas as pd
from urllib.parse import urlparse, urlunparse, quote
from requests.utils import requote_uri

# ------------- config -------------
TRONCO_FILE = "tranco_7NZNX.csv"   # <-- change if needed
OUTPUT_10   = "tranco_dataset_10.csv"
OUTPUT_100  = "tranco_dataset_100.csv"
OUTPUT_FULL = "tranco_dataset_full.csv"

CONNECTIONS = 100             # parallel workers
HTTP_CONNECT_TIMEOUT = 2.0    # seconds to connect
HTTP_READ_TIMEOUT    = 2.0    # seconds to read
TIMEOUT = (HTTP_CONNECT_TIMEOUT, HTTP_READ_TIMEOUT)
UA = {"User-Agent": "Mozilla/5.0 (compatible; MScTrancoExtractor/1.0)"}

SIGNS = [".","-","_","/","?","=","@","&","!"," ","~","˜",",","+","*","#","$","%"]
SIGN_LABELS = {
    ".":"dot","-":"hyphen","_":"underline","/":"slash","?":"questionmark","=":"equal",
    "@":"at","&":"and","!":"exclamation"," ":"space","~":"tilde","˜":"tilde",",":"comma",
    "+":"plus","*":"asterisk","#":"hashtag","$":"dollar","%":"percent"
}

# ------------- helpers -------------
def normalize_url(u: str) -> str:
    s = (str(u) or "").strip()
    if not s: return ""
    if s.startswith("//"): s = "http:" + s
    if "://" not in s: s = "http://" + s
    p = urlparse(s)
    if not p.netloc and p.path:
        p = urlparse(f"{p.scheme}://{p.path}")
    host = p.hostname or ""
    port = p.port
    user = p.username or ""
    pwd  = p.password or ""
    userinfo = ""
    if user:
        userinfo = quote(user, safe="")
        if pwd: userinfo += ":" + quote(pwd, safe="")
        userinfo += "@"
    if ":" in host and not (host.startswith("[") and host.endswith("]")):
        host = f"[{host}]"
    netloc = userinfo + host + (f":{port}" if port else "")
    return requote_uri(urlunparse((p.scheme, netloc, p.path or "", p.params or "", p.query or "", p.fragment or "")))

def splitURL(url: str) -> dict:
    try:
        p = urlparse(normalize_url(url))
        directory = p.path or ""
        return {
            "domain":   p.hostname or "",
            "directory": directory,
            "file":      directory.split("/")[-1] if directory else "",
            "params":    p.query or "",
            "fragment":  p.fragment or "",
        }
    except Exception:
        return {"domain":"","directory":"","file":"","params":"","fragment":""}

def getCounts(text: str, signs: list, scope: str) -> dict:
    s = text if isinstance(text, str) else ""
    out = {}
    tilde_total, done = s.count("~") + s.count("˜"), False
    for ch in signs:
        token = SIGN_LABELS.get(ch, f"u{ord(ch)}"); col = f"qty_{token}_{scope}"
        if ch in ("~","˜"):
            if not done:
                out[col] = tilde_total; done = True
        else:
            out[col] = s.count(ch)
    if scope == "url": out["length_url"] = len(s)
    else: out[f"{scope}_length"] = len(s)
    return out

# ------------- parallel HTTP HEAD -------------
def _head_worker(url: str) -> dict:
    res = {
        "time_response": float("nan"),
        "qty_redirects": 0,
        "http_status": float("nan"),
        "server_header": "",
        "tls_ssl_certificate": 1 if normalize_url(url).lower().startswith("https") else 0,
    }
    try:
        t0 = time.perf_counter()
        r = requests.head(normalize_url(url), headers=UA, timeout=TIMEOUT, allow_redirects=True)
        res["time_response"] = int((time.perf_counter() - t0) * 1000)
        res["qty_redirects"] = len(r.history)
        res["http_status"]   = r.status_code
        res["server_header"] = r.headers.get("Server","")
    except requests.exceptions.Timeout:
        pass
    except Exception:
        pass
    return res

def fetch_features_parallel(urls, max_workers=CONNECTIONS):
    out = [None] * len(urls)
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(_head_worker, u): idx for idx, u in enumerate(urls)}
        done = 0; total = len(urls); step = max(1, total // 10)
        for fut in concurrent.futures.as_completed(futures):
            idx = futures[fut]
            try:
                out[idx] = fut.result()
            except Exception:
                out[idx] = _head_worker("")
            done += 1
            if done % step == 0 or done == total:
                print(f"  HEAD progress: {done}/{total}")
    return out

# ------------- Algorithm 1 runner for Tranco -------------
def run_tranco_algorithm(tranco_csv=TRONCO_FILE, limit=None, output_csv="tranco_dataset.csv"):
    # Load tranco (Rank,Domain) -> URL + Label=0
    tdf = pd.read_csv(tranco_csv, header=None, names=["Rank","Domain"])
    tdf["URL"] = "http://" + tdf["Domain"].astype(str)
    tdf["Label"] = 0  # benign
    urls = tdf["URL"].astype(str).tolist()
    if limit is not None: urls = urls[:limit]
    total = len(urls)
    print(f"\n Tranco Algorithm 1 on {total} URLs (parallel HEAD={CONNECTIONS}, timeout={TIMEOUT})")

    # Step 9 (external) in parallel first
    head_feats = fetch_features_parallel(urls, max_workers=CONNECTIONS)

    # Steps 5–8 + TLD extraction
    rows = []
    i = 0
    while i < total:
        url = urls[i]
        row = {"url": url, "Label": 0}

        # URL-wide counts
        row.update(getCounts(url, SIGNS, "url"))

        # substrings (domain, directory, file, params, fragment)
        parts = splitURL(url)
        for scope, sub in parts.items():
            row.update(getCounts(sub, SIGNS, scope))

        # explicit TLD + its length
        dom = parts["domain"]
        row["tld"] = dom.split(".")[-1] if "." in dom else ""
        row["qty_tld_url"] = len(row["tld"])

        # cached HEAD metrics
        row.update(head_feats[i] if head_feats[i] else _head_worker(""))

        rows.append(row)
        if i % max(1, total // 10) == 0 or i == total - 1:
            print(f"  Build progress: {i+1}/{total}")
        i += 1

    out_df = pd.DataFrame(rows)
    out_df.to_csv(output_csv, index=False)
    print(f"\nDone! Wrote {total} rows → {output_csv}")
    display(out_df.head(10))
    return out_df

# ---------------- RUNS ----------------
# First 10
#df_tranco_10  = run_tranco_algorithm(TRONCO_FILE, limit=10,  output_csv=OUTPUT_10)

# First 100
#df_tranco_100 = run_tranco_algorithm(TRONCO_FILE, limit=100, output_csv=OUTPUT_100)

# Full dataset
df_tranco_full = run_tranco_algorithm(TRONCO_FILE, limit=None, output_csv=OUTPUT_FULL)''''''''''

 Tranco Algorithm 1 on 1000000 URLs (parallel HEAD=100, timeout=(2.0, 2.0))

WARNING:urllib3.response:Received response with both Content-Length and Transfer-Encoding set. This is expressly forbidden by RFC 7230 sec 3.3.2. Ignoring Content-Length and attempting to process response as Transfer-Encoding: chunked.
WARNING:urllib3.connection:Failed to parse headers (url=https://www.deepfreeze.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src blob: 'unsafe-inline' 'unsafe-eval' 'self' https://*.uservoice.com https://maps.googleapis.com https://faronics.kayako.com/ https://apis.google.com/; connect-src https: 'self' ws:; img-src blob: https: 'self' data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 16:40:54 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src blob: 'unsafe-inline' 'unsafe-eval' 'self' https://*.uservoice.com https://maps.googleapis.com https://faronics.kayako.com/ https://apis.google.com/; connect-src https: 'self' ws:; img-src blob: https: 'self' data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 16:40:54 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://www.deepfreeze.com:443/en/Account/Login): [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src blob: 'unsafe-inline' 'unsafe-eval' 'self' https://*.uservoice.com https://maps.googleapis.com https://faronics.kayako.com/ https://apis.google.com/; connect-src https: 'self' ws:; img-src blob: https: 'self' data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 16:40:55 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src blob: 'unsafe-inline' 'unsafe-eval' 'self' https://*.uservoice.com https://maps.googleapis.com https://faronics.kayako.com/ https://apis.google.com/; connect-src https: 'self' ws:; img-src blob: https: 'self' data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 16:40:55 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://www.deepfreeze.com:443/Error/CatchError?aspxerrorpath=/en/Account/Login): [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src blob: 'unsafe-inline' 'unsafe-eval' 'self' https://*.uservoice.com https://maps.googleapis.com https://faronics.kayako.com/ https://apis.google.com/; connect-src https: 'self' ws:; img-src blob: https: 'self' data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 16:40:55 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src blob: 'unsafe-inline' 'unsafe-eval' 'self' https://*.uservoice.com https://maps.googleapis.com https://faronics.kayako.com/ https://apis.google.com/; connect-src https: 'self' ws:; img-src blob: https: 'self' data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 16:40:55 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://customers.clouditalia.com:443/cgi-bin/wbc_logonopenservice?wc_retpath=https%3A%2F%2Fareaclienti.clouditalia.com%2Findex.php%3Foption%3Dcom_content%26task%3Dview%26id%3D6%26Itemid%3D63): [MissingHeaderBodySeparatorDefect()], unparsed data: '(offline mode: enter name=value pairs on standard input)\r\nSet-Cookie: wc_databaseos="dbeutelia";domain=clouditalia.com;PATH=/;\r\nSet-Cookie: pk_lang="italiano";domain=clouditalia.com;PATH=/;\r\nVary: Accept-Encoding\r\nContent-Encoding: gzip\r\nContent-Length: 1989\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '(offline mode: enter name=value pairs on standard input)\r\nSet-Cookie: wc_databaseos="dbeutelia";domain=clouditalia.com;PATH=/;\r\nSet-Cookie: pk_lang="italiano";domain=clouditalia.com;PATH=/;\r\nVary: Accept-Encoding\r\nContent-Encoding: gzip\r\nContent-Length: 1989\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://buet.ac.bd:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'engine X: nginx\r\nDate: Wed, 15 Oct 2025 16:46:48 GMT\r\nConnection: close\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'engine X: nginx\r\nDate: Wed, 15 Oct 2025 16:46:48 GMT\r\nConnection: close\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://dirtrab.cl:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'â\x80\x9cX-Frame-Optionsâ\x80\x9d: SAMEORIGIN\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'â\x80\x9cX-Frame-Optionsâ\x80\x9d: SAMEORIGIN\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.bella.tw:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'x-frame-options DENY: \r\nConnection: keep-alive\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'x-frame-options DENY: \r\nConnection: keep-alive\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://iob.in:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Cache-Control : max-age=31536000 Age= 86400\r\nX-XSS-Protection: 1; mode=block\r\nX-Permitted-Cross-Domain-Policies: none\r\nStrict-Transport-Security: max-age=31536000\r\nReferrer-Policy: no-referrer\r\nFeature-Policy: fullscreen 'none', microphone 'none', camera 'none' , geolocation 'self'\r\nPermission-Policy: geolocation=(self), vibrate=()\r\nDate: Wed, 15 Oct 2025 16:51:23 GMT\r\nConnection: close\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "Cache-Control : max-age=31536000 Age= 86400\r\nX-XSS-Protection: 1; mode=block\r\nX-Permitted-Cross-Domain-Policies: none\r\nStrict-Transport-Security: max-age=31536000\r\nReferrer-Policy: no-referrer\r\nFeature-Policy: fullscreen 'none', microphone 'none', camera 'none' , geolocation 'self'\r\nPermission-Policy: geolocation=(self), vibrate=()\r\nDate: Wed, 15 Oct 2025 16:51:23 GMT\r\nConnection: close\r\n\r\n"

  HEAD progress: 100000/1000000

WARNING:urllib3.connection:Failed to parse headers (url=http://www.armyneedyou.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
WARNING:urllib3.response:Received response with both Content-Length and Transfer-Encoding set. This is expressly forbidden by RFC 7230 sec 3.3.2. Ignoring Content-Length and attempting to process response as Transfer-Encoding: chunked.
WARNING:urllib3.connection:Failed to parse headers (url=https://www.banquelaurentienne.ca:443/fr): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\nTransfer-Encoding: chunked\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\nTransfer-Encoding: chunked\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://shoegalleryonline.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:03:53 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:03:53 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.shoegalleryonline.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:03:53 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:03:53 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://paesionline.it:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : DENY\r\nDate: Wed, 15 Oct 2025 17:09:49 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : DENY\r\nDate: Wed, 15 Oct 2025 17:09:49 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://www.paesionline.it:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : DENY\r\nDate: Wed, 15 Oct 2025 17:09:50 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : DENY\r\nDate: Wed, 15 Oct 2025 17:09:50 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.paesionline.it:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : DENY\r\nDate: Wed, 15 Oct 2025 17:09:51 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : DENY\r\nDate: Wed, 15 Oct 2025 17:09:51 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://ynshangji.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Expires : 0\r\nContent-Security-Policy: object-src 'none'; \r\nStrict-Transport-Security: max-age=31536000;includeSubDomains\r\nDate: Wed, 15 Oct 2025 17:11:01 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "Expires : 0\r\nContent-Security-Policy: object-src 'none'; \r\nStrict-Transport-Security: max-age=31536000;includeSubDomains\r\nDate: Wed, 15 Oct 2025 17:11:01 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://www.farmershomefurniture.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:11:27 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:11:27 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://www.artofwarios.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.aapm.org:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 6.1: 9269493000\r\nDate: Wed, 15 Oct 2025 17:14:20 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 6.1: 9269493000\r\nDate: Wed, 15 Oct 2025 17:14:20 GMT\r\n\r\n'

  HEAD progress: 200000/1000000

WARNING:urllib3.connection:Failed to parse headers (url=http://glwiz.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'pdf downloader: Content-Disposition: attachment; filename=<https://www.glwiz.com/guide/GLWiZ-RechargeCard-Guide.pdf>\r\nDate: Wed, 15 Oct 2025 17:18:14 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'pdf downloader: Content-Disposition: attachment; filename=<https://www.glwiz.com/guide/GLWiZ-RechargeCard-Guide.pdf>\r\nDate: Wed, 15 Oct 2025 17:18:14 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://antenne.at:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: "'self' 'unsafe-inline'; img-src 'self' data:;\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "'self' 'unsafe-inline'; img-src 'self' data:;\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=http://haedongacademy.org:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nSet-Cookie: PHPSESSID=93741a157032d48f3eac5f398935aa20; path=/\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nSet-Cookie: PHPSESSID=93741a157032d48f3eac5f398935aa20; path=/\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://oto.cc:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: '<html><body><h1>404 Not Found</h1>\n</body></html>\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '<html><body><h1>404 Not Found</h1>\n</body></html>\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://odu.edu.tr:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Permissions-Policy\t: geolocation=(), microphone=(), camera=()\r\nDate: Wed, 15 Oct 2025 17:29:09 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Permissions-Policy\t: geolocation=(), microphone=(), camera=()\r\nDate: Wed, 15 Oct 2025 17:29:09 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://odu.edu.tr:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Permissions-Policy\t: geolocation=(), microphone=(), camera=()\r\nDate: Wed, 15 Oct 2025 17:29:09 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Permissions-Policy\t: geolocation=(), microphone=(), camera=()\r\nDate: Wed, 15 Oct 2025 17:29:09 GMT\r\n\r\n'

  HEAD progress: 300000/1000000

WARNING:urllib3.connection:Failed to parse headers (url=https://ideastage.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:32:28 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:32:28 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.ideastage.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=41fd31e2-162f-491c-bb7f-7156d10a73e0; expires=Thu, 15-Oct-2026 17:32:29 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=u2iujywd044kfe2lxryyyr1u; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:32:29 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=41fd31e2-162f-491c-bb7f-7156d10a73e0; expires=Thu, 15-Oct-2026 17:32:29 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=u2iujywd044kfe2lxryyyr1u; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:32:29 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.ideastage.com:443/home): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=29806949-2fb6-4853-9b51-91c9dc062cae; expires=Thu, 15-Oct-2026 17:32:29 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=bhimua3sy01sbiw5fdgcb4xu; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:32:29 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=29806949-2fb6-4853-9b51-91c9dc062cae; expires=Thu, 15-Oct-2026 17:32:29 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=bhimua3sy01sbiw5fdgcb4xu; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:32:29 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://kcm.kr:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nSet-Cookie: PHPSESSID=d0fe7d77569e290d0b8302c9c4ca3f23; path=/\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nSet-Cookie: PHPSESSID=d0fe7d77569e290d0b8302c9c4ca3f23; path=/\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://waltrop.de:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Expect-CT, report-uri="https://services.gkd-re.de/policyreports": enforce, max-age=30\r\nFeature-Policy: geolocation \'none\'; midi \'none\'; notifications \'none\'; push \'none\'; sync-xhr \'none\'; microphone \'none\'; camera \'none\'; magnetometer \'none\'; gyroscope \'none\'; speaker \'none\'; vibrate \'none\'; fullscreen \'self\'; payment \'none\';\r\nReferrer-Policy: same-origin\r\nStrict-Transport-Security: max-age=31536000\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:34:31 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Expect-CT, report-uri="https://services.gkd-re.de/policyreports": enforce, max-age=30\r\nFeature-Policy: geolocation \'none\'; midi \'none\'; notifications \'none\'; push \'none\'; sync-xhr \'none\'; microphone \'none\'; camera \'none\'; magnetometer \'none\'; gyroscope \'none\'; speaker \'none\'; vibrate \'none\'; fullscreen \'self\'; payment \'none\';\r\nReferrer-Policy: same-origin\r\nStrict-Transport-Security: max-age=31536000\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:34:31 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.waltrop.de:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Expect-CT, report-uri="https://services.gkd-re.de/policyreports": enforce, max-age=30\r\nFeature-Policy: geolocation \'none\'; midi \'none\'; notifications \'none\'; push \'none\'; sync-xhr \'none\'; microphone \'none\'; camera \'none\'; magnetometer \'none\'; gyroscope \'none\'; speaker \'none\'; vibrate \'none\'; fullscreen \'self\'; payment \'none\';\r\nReferrer-Policy: same-origin\r\nStrict-Transport-Security: max-age=31536000\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:34:32 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Expect-CT, report-uri="https://services.gkd-re.de/policyreports": enforce, max-age=30\r\nFeature-Policy: geolocation \'none\'; midi \'none\'; notifications \'none\'; push \'none\'; sync-xhr \'none\'; microphone \'none\'; camera \'none\'; magnetometer \'none\'; gyroscope \'none\'; speaker \'none\'; vibrate \'none\'; fullscreen \'self\'; payment \'none\';\r\nReferrer-Policy: same-origin\r\nStrict-Transport-Security: max-age=31536000\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:34:32 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.waltrop.de:443/Inhalte/Ueber_Waltrop/aktuelles.asp): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Expect-CT, report-uri="https://services.gkd-re.de/policyreports": enforce, max-age=30\r\nFeature-Policy: geolocation \'none\'; midi \'none\'; notifications \'none\'; push \'none\'; sync-xhr \'none\'; microphone \'none\'; camera \'none\'; magnetometer \'none\'; gyroscope \'none\'; speaker \'none\'; vibrate \'none\'; fullscreen \'self\'; payment \'none\';\r\nReferrer-Policy: same-origin\r\nStrict-Transport-Security: max-age=31536000\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:34:32 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Expect-CT, report-uri="https://services.gkd-re.de/policyreports": enforce, max-age=30\r\nFeature-Policy: geolocation \'none\'; midi \'none\'; notifications \'none\'; push \'none\'; sync-xhr \'none\'; microphone \'none\'; camera \'none\'; magnetometer \'none\'; gyroscope \'none\'; speaker \'none\'; vibrate \'none\'; fullscreen \'self\'; payment \'none\';\r\nReferrer-Policy: same-origin\r\nStrict-Transport-Security: max-age=31536000\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:34:32 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://orbisx.ca:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: '301 Moved Permanently: \r\nLocation: /app/dashboard\r\nServer: F\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '301 Moved Permanently: \r\nLocation: /app/dashboard\r\nServer: F\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://kcm.co.kr:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nSet-Cookie: PHPSESSID=9861909ca74cb238d934f679e51939e0; path=/\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nSet-Cookie: PHPSESSID=9861909ca74cb238d934f679e51939e0; path=/\r\nKeep-Alive: timeout=15, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html\r\n\r\n'
WARNING:urllib3.response:Received response with both Content-Length and Transfer-Encoding set. This is expressly forbidden by RFC 7230 sec 3.3.2. Ignoring Content-Length and attempting to process response as Transfer-Encoding: chunked.
WARNING:urllib3.connection:Failed to parse headers (url=http://www.artofwarconquest.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.yakup.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nExpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nLast-Modified: Wed, 15 Oct 2025 17:47:33 GMT\r\nCache-Control: no-store, no-cache, must-revalidate\r\nPragma: no-cache\r\nSet-Cookie: PHPSESSID=3p6kpfsl4pgho1tpd4ddkrfvj2; path=/\r\nSet-Cookie: df_count_flag=1; path=/\r\nVary: User-Agent\r\nKeep-Alive: timeout=5, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'P3P : CP="ALL CURa ADMa DEVa TAIa OUR BUS IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC OTC"\r\nExpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nLast-Modified: Wed, 15 Oct 2025 17:47:33 GMT\r\nCache-Control: no-store, no-cache, must-revalidate\r\nPragma: no-cache\r\nSet-Cookie: PHPSESSID=3p6kpfsl4pgho1tpd4ddkrfvj2; path=/\r\nSet-Cookie: df_count_flag=1; path=/\r\nVary: User-Agent\r\nKeep-Alive: timeout=5, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.helpteaching.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'https 200 OK: \r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'https 200 OK: \r\nContent-Encoding: gzip\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://billandpauls.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:47:44 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:47:44 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.billandpauls.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:47:46 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 17:47:46 GMT\r\n\r\n'

  HEAD progress: 400000/1000000

WARNING:urllib3.response:Received response with both Content-Length and Transfer-Encoding set. This is expressly forbidden by RFC 7230 sec 3.3.2. Ignoring Content-Length and attempting to process response as Transfer-Encoding: chunked.
WARNING:urllib3.connection:Failed to parse headers (url=https://trexis.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Header set Content-Security-Policy: default-src 'self'\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nStrict-Transport-Security: max-age=31536000\r\nContent-Security-Policy: default-src 'self' 'unsafe-inline' https://acsbapp.com https://fonts.gstatic.com https://capture.trackjs.com https://google-analytics.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://www.googletagmanager.com googletagmanager.com; img-src 'self' data: blob: https://streetviewpixels-pa.googleapis.com https://lh3.ggpht.com https://khms0.googleapis.com https://khms1.googleapis.com https://whoson.alfapolicy.com:444 https://usage.trackjs.com https://maps.gstatic.com https://maps.googleapis.com https://maps.google.com https://www.google-analytics.com https://google-analytics.com https://www.googletagmanager.com https://googletagmanager.com; script-src 'self' https://acsbapp.com https://cdn.trackjs.com https://eapi.trexis.com https://portalone.processonepayments.com https://www.googleapis.com https://www.google-analytics.com https://www.googletagmanager.com https://maps.google.com https://maps.googleapis.com/ https://googletagmanager.com https://google-analytics.com 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://eapi.trexis.com https://portalone.processonepayments.com https://cdn.acsbapp.com https://capture.trackjs.com https://www.google-analytics.com https://maps.googleapis.com https://analytics.google.com; frame-src 'self' *.trexis.com trexis.com https://www.tranzpay.com https://portalone.processonepayments.com https://pronto.alfapolicy.com; object-src 'none'; base-uri 'self'; frame-ancestors https://rtr.trexis.com https://www.trexis.com https://trexis.com;\r\nX-AspNetMvc-Version: \r\nDate: Wed, 15 Oct 2025 17:53:08 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "Header set Content-Security-Policy: default-src 'self'\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nStrict-Transport-Security: max-age=31536000\r\nContent-Security-Policy: default-src 'self' 'unsafe-inline' https://acsbapp.com https://fonts.gstatic.com https://capture.trackjs.com https://google-analytics.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://www.googletagmanager.com googletagmanager.com; img-src 'self' data: blob: https://streetviewpixels-pa.googleapis.com https://lh3.ggpht.com https://khms0.googleapis.com https://khms1.googleapis.com https://whoson.alfapolicy.com:444 https://usage.trackjs.com https://maps.gstatic.com https://maps.googleapis.com https://maps.google.com https://www.google-analytics.com https://google-analytics.com https://www.googletagmanager.com https://googletagmanager.com; script-src 'self' https://acsbapp.com https://cdn.trackjs.com https://eapi.trexis.com https://portalone.processonepayments.com https://www.googleapis.com https://www.google-analytics.com https://www.googletagmanager.com https://maps.google.com https://maps.googleapis.com/ https://googletagmanager.com https://google-analytics.com 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://eapi.trexis.com https://portalone.processonepayments.com https://cdn.acsbapp.com https://capture.trackjs.com https://www.google-analytics.com https://maps.googleapis.com https://analytics.google.com; frame-src 'self' *.trexis.com trexis.com https://www.tranzpay.com https://portalone.processonepayments.com https://pronto.alfapolicy.com; object-src 'none'; base-uri 'self'; frame-ancestors https://rtr.trexis.com https://www.trexis.com https://trexis.com;\r\nX-AspNetMvc-Version: \r\nDate: Wed, 15 Oct 2025 17:53:08 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=http://knappschaft-kliniken.de:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 7.03: 9301487000\r\nDate: Wed, 15 Oct 2025 17:53:33 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 7.03: 9301487000\r\nDate: Wed, 15 Oct 2025 17:53:33 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.knappschaft-kliniken.de:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 7.03: 9301487000\r\nAuthentiX Version 7.03: 9301487000\r\nDate: Wed, 15 Oct 2025 17:53:34 GMT\r\nStrict-Transport-Security: max-age=31536000\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 7.03: 9301487000\r\nAuthentiX Version 7.03: 9301487000\r\nDate: Wed, 15 Oct 2025 17:53:34 GMT\r\nStrict-Transport-Security: max-age=31536000\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://mundodanone.com.br:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nStrict-Transport-Security: max-age=63072000; includeSubDomains; preload\r\nX-Content-Type-Options : nosniff\r\nX-Frame-Options: SAMEORIGIN\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:58:26 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nStrict-Transport-Security: max-age=63072000; includeSubDomains; preload\r\nX-Content-Type-Options : nosniff\r\nX-Frame-Options: SAMEORIGIN\r\nX-XSS-Protection: 1; mode=block\r\nDate: Wed, 15 Oct 2025 17:58:26 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://brilliantpromos.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:58:57 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:58:57 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.brilliantpromos.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=cb3ae5a8-c72a-4bd1-986a-6a9d468b8070; expires=Thu, 15-Oct-2026 17:58:59 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=kumotndzuis45xv0uq1az1bo; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:58:58 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=cb3ae5a8-c72a-4bd1-986a-6a9d468b8070; expires=Thu, 15-Oct-2026 17:58:59 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=kumotndzuis45xv0uq1az1bo; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:58:58 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.brilliantpromos.com:443/BP-Home): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=bf976d28-77e9-40d2-95eb-a1a55e405590; expires=Thu, 15-Oct-2026 17:58:59 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=r23zlf4gsgiavhyvkbjrd5vb; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:58:59 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : DENY\r\nSet-Cookie: webuser=UserGUID=bf976d28-77e9-40d2-95eb-a1a55e405590; expires=Thu, 15-Oct-2026 17:58:59 GMT; path=/; secure\r\nSet-Cookie: ASP.NET_SessionId=r23zlf4gsgiavhyvkbjrd5vb; path=/; secure; HttpOnly; SameSite=Lax\r\nX-Powered-By: \r\nDate: Wed, 15 Oct 2025 17:58:59 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.stout.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Content Security Policy: default-src 'self' https://apps.sitecore.net; script-src 'self' https://tracker.mnixdata.com/pixel.js  https://js.hubspot.com https://www.buzzsprout.com  https://www.clarity.ms https://tags.clickagy.com https://bat.bing.com https://js.hsadspixel.net/fb.js https://embed.typeform.com/next/embed.js https://ws.zoominfo.com/pixel/61d4c2aba49d55001c4da310 https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js https://www.googletagmanager.com/ https://www.google-analytics.com/debug/ https://platform.twitter.com/ https://cdn.syndication.twimg.com/ https://js.hs-analytics.net/analytics/1619106900000/4408380.js https://js.hs-banner.com/ https://js.hs-banner.com/4408380.js https://js.hs-scripts.com/4408380.js https://js.hsleadflows.net/leadflows.js https://play.vidyard.com/embed/v4.js https://snap.licdn.com/li.lms-analytics/ https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtm.js https://js.hsforms.net https://forms.hsforms.com/ https://www.google.com/recaptcha/enterprise.js https://www.gstatic.com/recaptcha/releases/Iwg4ANhK7Iu8SHToSsE0E20K/recaptcha__en.js https://platform-api.sharethis.com/js/sharethis.js https://buttons-config.sharethis.com/js/58b9eba59ea1120011539412.js js.hs-analytics.net https://www.gstatic.com/recaptcha/ *.sharethis.com *.vidyard.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com 'unsafe-inline'; img-src * 'unsafe-eval' 'unsafe-inline' data:; style-src * 'unsafe-inline'; media-src *; frame-src *; font-src *; connect-src 'self' www.googletagmanager.com https://px.ads.linkedin.com/ https://pixelconnector.mnixdata.com  https://bcp.crwdcntrl.net/6/map https://px.ads.linkedin.com/wa/ https://cta-service-cms2.hubspot.com https://cdn.linkedin.oribi.io/partner/1408092/domain/stout.com/token https://cdn.linkedin.oribi.io/partner/1408092/domain/pre-www.stout.com/token https://ws.zoominfo.com/pixel/collect https://js.hs-banner.com/cookie-banner-public/v1/activity/view *.google-analytics.com *.analytics.com *.clickagy.com *.clarity.ms https://api.hubapi.com/ https://forms.hubspot.com/ https://forms.hsforms.com/ https://www.google-analytics.com/ *.sharethis.com https://js.hs-banner.com/cookie-banner/activity/view https://js.hs-banner.com/cookie-banner-public/v1/domain-collection  https://js.hs-banner.com/cookie-banner-public/v2/activity/view https://js.hs-banner.com/cookie-banner-public/v1/activity/click; report-uri https://60819ca63ba5ce6a67745a2c.endpoint.csper.io/; upgrade-insecure-requests;\r\nDate: Wed, 15 Oct 2025 18:01:20 GMT\r\nX-FRAME-OPTIONS: SAMEORIGIN\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "Content Security Policy: default-src 'self' https://apps.sitecore.net; script-src 'self' https://tracker.mnixdata.com/pixel.js  https://js.hubspot.com https://www.buzzsprout.com  https://www.clarity.ms https://tags.clickagy.com https://bat.bing.com https://js.hsadspixel.net/fb.js https://embed.typeform.com/next/embed.js https://ws.zoominfo.com/pixel/61d4c2aba49d55001c4da310 https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js https://www.googletagmanager.com/ https://www.google-analytics.com/debug/ https://platform.twitter.com/ https://cdn.syndication.twimg.com/ https://js.hs-analytics.net/analytics/1619106900000/4408380.js https://js.hs-banner.com/ https://js.hs-banner.com/4408380.js https://js.hs-scripts.com/4408380.js https://js.hsleadflows.net/leadflows.js https://play.vidyard.com/embed/v4.js https://snap.licdn.com/li.lms-analytics/ https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtm.js https://js.hsforms.net https://forms.hsforms.com/ https://www.google.com/recaptcha/enterprise.js https://www.gstatic.com/recaptcha/releases/Iwg4ANhK7Iu8SHToSsE0E20K/recaptcha__en.js https://platform-api.sharethis.com/js/sharethis.js https://buttons-config.sharethis.com/js/58b9eba59ea1120011539412.js js.hs-analytics.net https://www.gstatic.com/recaptcha/ *.sharethis.com *.vidyard.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com 'unsafe-inline'; img-src * 'unsafe-eval' 'unsafe-inline' data:; style-src * 'unsafe-inline'; media-src *; frame-src *; font-src *; connect-src 'self' www.googletagmanager.com https://px.ads.linkedin.com/ https://pixelconnector.mnixdata.com  https://bcp.crwdcntrl.net/6/map https://px.ads.linkedin.com/wa/ https://cta-service-cms2.hubspot.com https://cdn.linkedin.oribi.io/partner/1408092/domain/stout.com/token https://cdn.linkedin.oribi.io/partner/1408092/domain/pre-www.stout.com/token https://ws.zoominfo.com/pixel/collect https://js.hs-banner.com/cookie-banner-public/v1/activity/view *.google-analytics.com *.analytics.com *.clickagy.com *.clarity.ms https://api.hubapi.com/ https://forms.hubspot.com/ https://forms.hsforms.com/ https://www.google-analytics.com/ *.sharethis.com https://js.hs-banner.com/cookie-banner/activity/view https://js.hs-banner.com/cookie-banner-public/v1/domain-collection  https://js.hs-banner.com/cookie-banner-public/v2/activity/view https://js.hs-banner.com/cookie-banner-public/v1/activity/click; report-uri https://60819ca63ba5ce6a67745a2c.endpoint.csper.io/; upgrade-insecure-requests;\r\nDate: Wed, 15 Oct 2025 18:01:20 GMT\r\nX-FRAME-OPTIONS: SAMEORIGIN\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://www.stout.com:443/en/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Content Security Policy: default-src 'self' https://apps.sitecore.net; script-src 'self' https://tracker.mnixdata.com/pixel.js  https://js.hubspot.com https://www.buzzsprout.com  https://www.clarity.ms https://tags.clickagy.com https://bat.bing.com https://js.hsadspixel.net/fb.js https://embed.typeform.com/next/embed.js https://ws.zoominfo.com/pixel/61d4c2aba49d55001c4da310 https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js https://www.googletagmanager.com/ https://www.google-analytics.com/debug/ https://platform.twitter.com/ https://cdn.syndication.twimg.com/ https://js.hs-analytics.net/analytics/1619106900000/4408380.js https://js.hs-banner.com/ https://js.hs-banner.com/4408380.js https://js.hs-scripts.com/4408380.js https://js.hsleadflows.net/leadflows.js https://play.vidyard.com/embed/v4.js https://snap.licdn.com/li.lms-analytics/ https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtm.js https://js.hsforms.net https://forms.hsforms.com/ https://www.google.com/recaptcha/enterprise.js https://www.gstatic.com/recaptcha/releases/Iwg4ANhK7Iu8SHToSsE0E20K/recaptcha__en.js https://platform-api.sharethis.com/js/sharethis.js https://buttons-config.sharethis.com/js/58b9eba59ea1120011539412.js js.hs-analytics.net https://www.gstatic.com/recaptcha/ *.sharethis.com *.vidyard.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com 'unsafe-inline'; img-src * 'unsafe-eval' 'unsafe-inline' data:; style-src * 'unsafe-inline'; media-src *; frame-src *; font-src *; connect-src 'self' www.googletagmanager.com https://px.ads.linkedin.com/ https://pixelconnector.mnixdata.com  https://bcp.crwdcntrl.net/6/map https://px.ads.linkedin.com/wa/ https://cta-service-cms2.hubspot.com https://cdn.linkedin.oribi.io/partner/1408092/domain/stout.com/token https://cdn.linkedin.oribi.io/partner/1408092/domain/pre-www.stout.com/token https://ws.zoominfo.com/pixel/collect https://js.hs-banner.com/cookie-banner-public/v1/activity/view *.google-analytics.com *.analytics.com *.clickagy.com *.clarity.ms https://api.hubapi.com/ https://forms.hubspot.com/ https://forms.hsforms.com/ https://www.google-analytics.com/ *.sharethis.com https://js.hs-banner.com/cookie-banner/activity/view https://js.hs-banner.com/cookie-banner-public/v1/domain-collection  https://js.hs-banner.com/cookie-banner-public/v2/activity/view https://js.hs-banner.com/cookie-banner-public/v1/activity/click; report-uri https://60819ca63ba5ce6a67745a2c.endpoint.csper.io/; upgrade-insecure-requests;\r\nDate: Wed, 15 Oct 2025 18:01:20 GMT\r\nX-FRAME-OPTIONS: SAMEORIGIN\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)

  HEAD progress: 500000/1000000

WARNING:urllib3.connection:Failed to parse headers (url=http://everymantheatre.org.uk:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Expose-Headers : WWW-Authenticate\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE\r\nAccess-Control-Allow-Headers: accept, authorization, Content-Type\r\nDate: Wed, 15 Oct 2025 18:10:54 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Expose-Headers : WWW-Authenticate\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE\r\nAccess-Control-Allow-Headers: accept, authorization, Content-Type\r\nDate: Wed, 15 Oct 2025 18:10:54 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.everymantheatre.org.uk:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Expose-Headers : WWW-Authenticate\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE\r\nAccess-Control-Allow-Headers: accept, authorization, Content-Type\r\nDate: Wed, 15 Oct 2025 18:10:54 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Expose-Headers : WWW-Authenticate\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE\r\nAccess-Control-Allow-Headers: accept, authorization, Content-Type\r\nDate: Wed, 15 Oct 2025 18:10:54 GMT\r\n\r\n'
WARNING:urllib3.response:Received response with both Content-Length and Transfer-Encoding set. This is expressly forbidden by RFC 7230 sec 3.3.2. Ignoring Content-Length and attempting to process response as Transfer-Encoding: chunked.
WARNING:urllib3.connection:Failed to parse headers (url=http://radioflamingo.at:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: "'self' 'unsafe-inline'; img-src 'self' data:;\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "'self' 'unsafe-inline'; img-src 'self' data:;\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=http://pedigreeskishop.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:16:04 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:16:04 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.pedigreeskishop.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:16:04 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:16:04 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://www.myblockpuzzleios.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://eulji.ac.kr:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer Policy: strict-orgin-when-cross-origin\r\nContent-Language: ko-KR\r\nSet-Cookie: SCOUTER=x17ura0j333m1j; path=/; expires=Mon, 02-Nov-2093 21:37:23 GMT\r\nSet-Cookie: JSESSIONID=baa0quNlUCOgFc29VAwLz; path=/; HttpOnly\r\nContent-Type: text/html; charset=utf-8\r\nDate: Wed, 15 Oct 2025 18:23:16 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer Policy: strict-orgin-when-cross-origin\r\nContent-Language: ko-KR\r\nSet-Cookie: SCOUTER=x17ura0j333m1j; path=/; expires=Mon, 02-Nov-2093 21:37:23 GMT\r\nSet-Cookie: JSESSIONID=baa0quNlUCOgFc29VAwLz; path=/; HttpOnly\r\nContent-Type: text/html; charset=utf-8\r\nDate: Wed, 15 Oct 2025 18:23:16 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.frasersproperty.com.au:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Cache Control: no-store\r\ninstanceID: 1\r\nDate: Wed, 15 Oct 2025 18:26:37 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Cache Control: no-store\r\ninstanceID: 1\r\nDate: Wed, 15 Oct 2025 18:26:37 GMT\r\n\r\n'

  HEAD progress: 600000/1000000

WARNING:urllib3.connection:Failed to parse headers (url=http://nmrcnoida.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Origin : nmrccms.datahosts.in\r\nDate: Wed, 15 Oct 2025 18:34:30 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Origin : nmrccms.datahosts.in\r\nDate: Wed, 15 Oct 2025 18:34:30 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://nmrcnoida.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Origin : nmrccms.datahosts.in\r\nDate: Wed, 15 Oct 2025 18:34:31 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Origin : nmrccms.datahosts.in\r\nDate: Wed, 15 Oct 2025 18:34:31 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://bullseyenorth.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:35:14 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:35:14 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.bullseyenorth.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:35:14 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:35:14 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://msmemart.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src 'self'; connect-src *; font-src *; frame-src *; img-src * data:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';\r\nX-Powered-By: MSME\r\nReferrer-Policy: same-origin\r\nDate: Wed, 15 Oct 2025 18:36:03 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src 'self'; connect-src *; font-src *; frame-src *; img-src * data:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';\r\nX-Powered-By: MSME\r\nReferrer-Policy: same-origin\r\nDate: Wed, 15 Oct 2025 18:36:03 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://msmemart.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src 'self'; connect-src *; font-src *; frame-src *; img-src * data:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';\r\nX-Powered-By: MSME\r\nReferrer-Policy: same-origin\r\nDate: Wed, 15 Oct 2025 18:36:05 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src 'self'; connect-src *; font-src *; frame-src *; img-src * data:; media-src *; object-src *; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline';\r\nX-Powered-By: MSME\r\nReferrer-Policy: same-origin\r\nDate: Wed, 15 Oct 2025 18:36:05 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://www.laurentianbank.ca:443/en): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Content-Type-Optionx-frame-options : SAMEORIGIN"\r\nx-xss-protection: 0\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://e-mac.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Copy Rights: Chalhoub Sharepoint Team\r\nWServer: web2\r\nDate: Wed, 15 Oct 2025 18:36:44 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Copy Rights: Chalhoub Sharepoint Team\r\nWServer: web2\r\nDate: Wed, 15 Oct 2025 18:36:44 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://e-mac.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Copy Rights: Chalhoub Sharepoint Team\r\nWServer: web2\r\nDate: Wed, 15 Oct 2025 18:36:44 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Copy Rights: Chalhoub Sharepoint Team\r\nWServer: web2\r\nDate: Wed, 15 Oct 2025 18:36:44 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://www.e-mac.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Copy Rights: Chalhoub Sharepoint Team\r\nWServer: web2\r\nDate: Wed, 15 Oct 2025 18:36:44 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Copy Rights: Chalhoub Sharepoint Team\r\nWServer: web2\r\nDate: Wed, 15 Oct 2025 18:36:44 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://nevadatreasurer.gov:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP Strict-Transport-Security: max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:37:32 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP Strict-Transport-Security: max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:37:32 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://asiawebhosting.net:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Apache Web Server 2.0: Apache Web Server 2.0 / Linux RedHad\r\nDate: Wed, 15 Oct 2025 18:40:11 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Apache Web Server 2.0: Apache Web Server 2.0 / Linux RedHad\r\nDate: Wed, 15 Oct 2025 18:40:11 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://asiawebhosting.net:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Apache Web Server 2.0: Apache Web Server 2.0 / Linux RedHad\r\nDate: Wed, 15 Oct 2025 18:40:14 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Apache Web Server 2.0: Apache Web Server 2.0 / Linux RedHad\r\nDate: Wed, 15 Oct 2025 18:40:14 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://asiancandy.net:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 7.03: 9301487000\r\nAuthentiX Version 7.03: 9301487000\r\nDate: Wed, 15 Oct 2025 18:44:14 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'AuthentiX Version 7.03: 9301487000\r\nAuthentiX Version 7.03: 9301487000\r\nDate: Wed, 15 Oct 2025 18:44:14 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.faronicsdeploy.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.googleapis.com https://www.googletagmanager.com https://kit.fontawesome.com; connect-src https: 'self' ws:; img-src https: 'self' blob: data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://use.fontawesome.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 18:47:08 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "X-Content-Type-Options : nosniff\r\nContent-Security-Policy: default-src https:; script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.googleapis.com https://www.googletagmanager.com https://kit.fontawesome.com; connect-src https: 'self' ws:; img-src https: 'self' blob: data:; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://use.fontawesome.com; font-src https:;\r\nDate: Wed, 15 Oct 2025 18:47:08 GMT\r\n\r\n"

  HEAD progress: 700000/1000000

WARNING:urllib3.connection:Failed to parse headers (url=http://ssgecom.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Cache-Control header: no-cache\r\nX-Frame-Options: SAMEORIGIN\r\nDate: Wed, 15 Oct 2025 18:48:41 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Cache-Control header: no-cache\r\nX-Frame-Options: SAMEORIGIN\r\nDate: Wed, 15 Oct 2025 18:48:41 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://www.wordlinkstore.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://skicountrysports.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:51:39 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:51:39 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.skicountrysports.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:51:40 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options : SAMEORIGIN\r\nX-Content-Type-Options : nosniff\r\nX-Xss-Protection : 1; mode=block\r\nStrict-Transport-Security : max-age=31536000\r\nDate: Wed, 15 Oct 2025 18:51:40 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://bc.ac.kr:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Content-Ty'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Content-Ty'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.danishfamilysearch.dk:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Danish Family Search: 2.23 64-bit\r\nDate: Wed, 15 Oct 2025 18:52:59 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Danish Family Search: 2.23 64-bit\r\nDate: Wed, 15 Oct 2025 18:52:59 GMT\r\n\r\n'
WARNING:urllib3.response:Received response with both Content-Length and Transfer-Encoding set. This is expressly forbidden by RFC 7230 sec 3.3.2. Ignoring Content-Length and attempting to process response as Transfer-Encoding: chunked.
WARNING:urllib3.connection:Failed to parse headers (url=http://mwsco.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Content-Security-Policy : default-src 'self' 'unsafe-inline' mwsco.com http://www.mwsco.com https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.mwsco.com https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com https://www.gstatic.com ;img-src 'self' https://www.mwsco.com https://mwsco.com https://www.google-analytics.com https://www.facebook.com https://www.googletagmanager.com https://backgroundimages.concrete5.org https://backgroundimages.concretecms.com https://image.captchas.net/ data:;\r\nDate: Wed, 15 Oct 2025 18:54:59 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "Content-Security-Policy : default-src 'self' 'unsafe-inline' mwsco.com http://www.mwsco.com https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.mwsco.com https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com https://www.gstatic.com ;img-src 'self' https://www.mwsco.com https://mwsco.com https://www.google-analytics.com https://www.facebook.com https://www.googletagmanager.com https://backgroundimages.concrete5.org https://backgroundimages.concretecms.com https://image.captchas.net/ data:;\r\nDate: Wed, 15 Oct 2025 18:54:59 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://mwsco.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Content-Security-Policy : default-src 'self' 'unsafe-inline' mwsco.com http://www.mwsco.com https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.mwsco.com https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com https://www.gstatic.com ;img-src 'self' https://www.mwsco.com https://mwsco.com https://www.google-analytics.com https://www.facebook.com https://www.googletagmanager.com https://backgroundimages.concrete5.org https://backgroundimages.concretecms.com https://image.captchas.net/ data:;\r\nDate: Wed, 15 Oct 2025 18:54:59 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "Content-Security-Policy : default-src 'self' 'unsafe-inline' mwsco.com http://www.mwsco.com https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.mwsco.com https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com https://www.gstatic.com ;img-src 'self' https://www.mwsco.com https://mwsco.com https://www.google-analytics.com https://www.facebook.com https://www.googletagmanager.com https://backgroundimages.concrete5.org https://backgroundimages.concretecms.com https://image.captchas.net/ data:;\r\nDate: Wed, 15 Oct 2025 18:54:59 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=https://www.mwsco.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "Content-Security-Policy : default-src 'self' 'unsafe-inline' mwsco.com http://www.mwsco.com https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.mwsco.com https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com https://www.gstatic.com ;img-src 'self' https://www.mwsco.com https://mwsco.com https://www.google-analytics.com https://www.facebook.com https://www.googletagmanager.com https://backgroundimages.concrete5.org https://backgroundimages.concretecms.com https://image.captchas.net/ data:;\r\nDate: Wed, 15 Oct 2025 18:55:01 GMT\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "Content-Security-Policy : default-src 'self' 'unsafe-inline' mwsco.com http://www.mwsco.com https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.mwsco.com https://www.googletagmanager.com https://connect.facebook.net https://www.google-analytics.com https://www.gstatic.com ;img-src 'self' https://www.mwsco.com https://mwsco.com https://www.google-analytics.com https://www.facebook.com https://www.googletagmanager.com https://backgroundimages.concrete5.org https://backgroundimages.concretecms.com https://image.captchas.net/ data:;\r\nDate: Wed, 15 Oct 2025 18:55:01 GMT\r\n\r\n"
WARNING:urllib3.connection:Failed to parse headers (url=http://uppwd.gov.in:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options Custom Header: DENY\r\nX-Permitted-Cross-Domain-Policies: none\r\nReferrer-Policy: origin\r\nDate: Wed, 15 Oct 2025 18:55:13 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-Frame-Options Custom Header: DENY\r\nX-Permitted-Cross-Domain-Policies: none\r\nReferrer-Policy: origin\r\nDate: Wed, 15 Oct 2025 18:55:13 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://admincourt.go.th:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Apache/2.4.9 (Unix): Apache HTTP Server 2.4.9 / Debian\r\nDate: Wed, 15 Oct 2025 18:55:48 GMT\r\nSet-Cookie: visid_incap_3233672=iHKsT4UTRoKhIQZ3Cp3rTTLu72gAAAAAQUIPAAAAAADC1AqmBi3kmIesrZKYDgdm; expires=Thu, 15 Oct 2026 06:41:01 GMT; HttpOnly; path=/; Domain=.admincourt.go.th\r\nSet-Cookie: incap_ses_4555_3233672=iU5mZ2XAqw/L0Iu7o5w2PzPu72gAAAAAxwV31je8fv2emqCNUlvCpQ==; path=/; Domain=.admincourt.go.th\r\nX-CDN: Imperva\r\nX-Iinfo: 62-57737454-57737493 NNNN CT(224 467 0) RT(1760554547768 96) q(0 0 7 0) r(9 9) U6\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Apache/2.4.9 (Unix): Apache HTTP Server 2.4.9 / Debian\r\nDate: Wed, 15 Oct 2025 18:55:48 GMT\r\nSet-Cookie: visid_incap_3233672=iHKsT4UTRoKhIQZ3Cp3rTTLu72gAAAAAQUIPAAAAAADC1AqmBi3kmIesrZKYDgdm; expires=Thu, 15 Oct 2026 06:41:01 GMT; HttpOnly; path=/; Domain=.admincourt.go.th\r\nSet-Cookie: incap_ses_4555_3233672=iU5mZ2XAqw/L0Iu7o5w2PzPu72gAAAAAxwV31je8fv2emqCNUlvCpQ==; path=/; Domain=.admincourt.go.th\r\nX-CDN: Imperva\r\nX-Iinfo: 62-57737454-57737493 NNNN CT(224 467 0) RT(1760554547768 96) q(0 0 7 0) r(9 9) U6\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.danishfamilysearch.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Danish Family Search: 2.23 64-bit\r\nDate: Wed, 15 Oct 2025 18:58:08 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Danish Family Search: 2.23 64-bit\r\nDate: Wed, 15 Oct 2025 18:58:08 GMT\r\n\r\n'

  HEAD progress: 800000/1000000

WARNING:urllib3.response:Received response with both Content-Length and Transfer-Encoding set. This is expressly forbidden by RFC 7230 sec 3.3.2. Ignoring Content-Length and attempting to process response as Transfer-Encoding: chunked.
WARNING:urllib3.connection:Failed to parse headers (url=https://kacpr.org:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Origin : *\r\nAccess-Control-Allow-Origin-Methods : X-Requested-With, Content-Type\r\nKeep-Alive: timeout=5, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html;charset=utf-8\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Origin : *\r\nAccess-Control-Allow-Origin-Methods : X-Requested-With, Content-Type\r\nKeep-Alive: timeout=5, max=100\r\nConnection: Keep-Alive\r\nContent-Type: text/html;charset=utf-8\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://paymytv.in:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-XSS-Protection : 1;mode = block\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: Nosniff\r\nAccess-Control-Allow-Credentials: TRUE\r\n Access-Control-Allow-Origin: *\r\nDate: Wed, 15 Oct 2025 19:14:30 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-XSS-Protection : 1;mode = block\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: Nosniff\r\nAccess-Control-Allow-Credentials: TRUE\r\n Access-Control-Allow-Origin: *\r\nDate: Wed, 15 Oct 2025 19:14:30 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.paymytv.in:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-XSS-Protection : 1;mode = block\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: Nosniff\r\nAccess-Control-Allow-Credentials: TRUE\r\n Access-Control-Allow-Origin: *\r\nDate: Wed, 15 Oct 2025 19:14:30 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-XSS-Protection : 1;mode = block\r\nX-Frame-Options: DENY\r\nX-Content-Type-Options: Nosniff\r\nAccess-Control-Allow-Credentials: TRUE\r\n Access-Control-Allow-Origin: *\r\nDate: Wed, 15 Oct 2025 19:14:30 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://stlegerhomes.co.uk:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security    : max-age=31536000; includeSubdomains\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: sameorigin\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nDate: Wed, 15 Oct 2025 19:13:46 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security    : max-age=31536000; includeSubdomains\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: sameorigin\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nDate: Wed, 15 Oct 2025 19:13:46 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://stlegerhomes.co.uk:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security    : max-age=31536000; includeSubdomains\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: sameorigin\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nDate: Wed, 15 Oct 2025 19:13:46 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security    : max-age=31536000; includeSubdomains\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: sameorigin\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nDate: Wed, 15 Oct 2025 19:13:46 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.stlegerhomes.co.uk:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security    : max-age=31536000; includeSubdomains\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: sameorigin\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nDate: Wed, 15 Oct 2025 19:13:47 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security    : max-age=31536000; includeSubdomains\r\nX-Content-Type-Options: nosniff\r\nX-Frame-Options: sameorigin\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nDate: Wed, 15 Oct 2025 19:13:47 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://gis.maconnc.org:443/www.maconnc.org/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : SAMEORIGIN\r\nX-XSS-Protection: 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nDate: Wed, 15 Oct 2025 19:20:13 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-FRAME-OPTIONS : SAMEORIGIN\r\nX-XSS-Protection: 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nDate: Wed, 15 Oct 2025 19:20:13 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://royalresorts.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security : max-age=31536000; includeSubDomains; preload\r\nX-Frame-Options: SAMEORIGIN\r\nX-Xss-Protection: 1; mode=block\r\nX-ASPNET-VERSION: \r\nDate: Wed, 15 Oct 2025 19:21:09 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security : max-age=31536000; includeSubDomains; preload\r\nX-Frame-Options: SAMEORIGIN\r\nX-Xss-Protection: 1; mode=block\r\nX-ASPNET-VERSION: \r\nDate: Wed, 15 Oct 2025 19:21:09 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.royalresorts.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security : max-age=31536000; includeSubDomains; preload\r\nX-Frame-Options: SAMEORIGIN\r\nX-Xss-Protection: 1; mode=block\r\nX-ASPNET-VERSION: \r\nDate: Wed, 15 Oct 2025 19:21:10 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Strict-Transport-Security : max-age=31536000; includeSubDomains; preload\r\nX-Frame-Options: SAMEORIGIN\r\nX-Xss-Protection: 1; mode=block\r\nX-ASPNET-VERSION: \r\nDate: Wed, 15 Oct 2025 19:21:10 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://ticketline.sapo.pt:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: "base-uri 'self';: \r\nscript-src 'self' *.checkout.com analytics.tiktok.com *.ticketline.pt *.ticketline.sapo.pt;: \r\nscript-src-elem 'self' 'unsafe-inline' *.googleadservices.com *.checkout.com *.ticketline.pt ticketline.sapo.pt data: bars.sapo.pt js.sapo.pt *.google-analytics.com ajax.googleapis.com stats.g.doubleclick.net imgs.sapo.pt www.googletagmanager.com connect.facebook.net *.equalweb.com;\r\nframe-src 'self' *.googletagmanager.com *.checkout.com js.klarna.com osm.klarnaservices.com *.youtube.com *.equalweb.com;: \r\nstyle-src x.klarnacdn.net;: \r\nimg-src *.googleadservices.com www.google.pt;: \r\nobject-src 'none';: \r\nconnect-src 'self' *.ticketline.pt api.ticketline.pt analytics.tiktok.com *.google-analytics.com google.com *.google.pt *.google.com stats.g.doubleclick.net www.googletagmanager.com connect.facebook.net *.klarna.com *.equalweb.com;: \r\nprefetch-src api.ticketline.pt;: \r\nframe-ancestors 'none';: \r\nplugin-types application/pdf;: \r\nX-XSS-Protection: 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nReferrer-Policy: strict-origin\r\nPermissions-Policy: fullscreen=(self)\r\nContent-Encoding: gzip\r\n\r\n"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: "base-uri 'self';: \r\nscript-src 'self' *.checkout.com analytics.tiktok.com *.ticketline.pt *.ticketline.sapo.pt;: \r\nscript-src-elem 'self' 'unsafe-inline' *.googleadservices.com *.checkout.com *.ticketline.pt ticketline.sapo.pt data: bars.sapo.pt js.sapo.pt *.google-analytics.com ajax.googleapis.com stats.g.doubleclick.net imgs.sapo.pt www.googletagmanager.com connect.facebook.net *.equalweb.com;\r\nframe-src 'self' *.googletagmanager.com *.checkout.com js.klarna.com osm.klarnaservices.com *.youtube.com *.equalweb.com;: \r\nstyle-src x.klarnacdn.net;: \r\nimg-src *.googleadservices.com www.google.pt;: \r\nobject-src 'none';: \r\nconnect-src 'self' *.ticketline.pt api.ticketline.pt analytics.tiktok.com *.google-analytics.com google.com *.google.pt *.google.com stats.g.doubleclick.net www.googletagmanager.com connect.facebook.net *.klarna.com *.equalweb.com;: \r\nprefetch-src api.ticketline.pt;: \r\nframe-ancestors 'none';: \r\nplugin-types application/pdf;: \r\nX-XSS-Protection: 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nReferrer-Policy: strict-origin\r\nPermissions-Policy: fullscreen=(self)\r\nContent-Encoding: gzip\r\n\r\n"

  HEAD progress: 900000/1000000

WARNING:urllib3.connection:Failed to parse headers (url=http://danone.com.mx:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nX-Content-Type-Options : nosniff\r\nDate: Wed, 15 Oct 2025 19:28:17 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nX-Content-Type-Options : nosniff\r\nDate: Wed, 15 Oct 2025 19:28:17 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://danone.com.mx:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nX-Content-Type-Options : nosniff\r\nDate: Wed, 15 Oct 2025 19:28:19 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nX-Content-Type-Options : nosniff\r\nDate: Wed, 15 Oct 2025 19:28:19 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.danone.com.mx:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nX-Content-Type-Options : nosniff\r\nDate: Wed, 15 Oct 2025 19:28:20 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Referrer-Policy : same-origin\r\nX-Content-Type-Options : nosniff\r\nDate: Wed, 15 Oct 2025 19:28:20 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://miaokids.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Credentials : true\r\nCache-Control: no-cache, private\r\nDate: Wed, 15 Oct 2025 19:33:37 GMT\r\nSet-Cookie: laravel_session=eyJpdiI6ImZNeklCdjdFN0V2OHNNVk5GVnlcL3VnPT0iLCJ2YWx1ZSI6Imx5WVdZeE9YT2Vza0dmcERRRGlHelZBVnZGYkhqUFwvd00yZWFrdkFzNzZHT1ZTU1hzU1djeXo4TW9mWDhGNXFRZXdQc0RsQmNmTFJsa3o3Zk9lR0JuZz09IiwibWFjIjoiMTVhM2ZjOWIzMTQxZjBjYmQ0OTY2NGI0OTM1MGI0NTNiZThlNWVjMjdiYWI1ODZmNzliOGZiNzgxMGUzMzFlMSJ9; expires=Wed, 15-Oct-2025 21:33:37 GMT; Max-Age=7200; path=/; httponly\r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'Access-Control-Allow-Credentials : true\r\nCache-Control: no-cache, private\r\nDate: Wed, 15 Oct 2025 19:33:37 GMT\r\nSet-Cookie: laravel_session=eyJpdiI6ImZNeklCdjdFN0V2OHNNVk5GVnlcL3VnPT0iLCJ2YWx1ZSI6Imx5WVdZeE9YT2Vza0dmcERRRGlHelZBVnZGYkhqUFwvd00yZWFrdkFzNzZHT1ZTU1hzU1djeXo4TW9mWDhGNXFRZXdQc0RsQmNmTFJsa3o3Zk9lR0JuZz09IiwibWFjIjoiMTVhM2ZjOWIzMTQxZjBjYmQ0OTY2NGI0OTM1MGI0NTNiZThlNWVjMjdiYWI1ODZmNzliOGZiNzgxMGUzMzFlMSJ9; expires=Wed, 15-Oct-2025 21:33:37 GMT; Max-Age=7200; path=/; httponly\r\nContent-Encoding: gzip\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=https://www.deltadentalri.com:443/): [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-XSS-Protection : 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nCross-Origin-Opener-Policy: same-origin-allow-popups\r\nDate: Wed, 15 Oct 2025 19:33:47 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'X-XSS-Protection : 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nReferrer-Policy: strict-origin-when-cross-origin\r\nCross-Origin-Opener-Policy: same-origin-allow-popups\r\nDate: Wed, 15 Oct 2025 19:33:47 GMT\r\n\r\n'
WARNING:urllib3.connection:Failed to parse headers (url=http://www.wordlinkplay.com:80/): [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 568, in getresponse
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/response.py", line 88, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: '404 Not Found: \r\nContent-Encoding: gzip\r\n\r\n'

**Final merged dataset of the features**

In [ ]:
import pandas as pd

# Load the two datasets
df_phishing = pd.read_csv("dataset_full (2).csv")
df_tranco = pd.read_csv("tranco_dataset_full.csv")

# Concatenate the dataframes
merged_df = pd.concat([df_phishing, df_tranco], ignore_index=True)

# Convert 'Label' column to boolean
merged_df['Label'] = merged_df['Label'].astype(bool)


# Display the first few rows of the merged dataframe
print("Merged dataset shape:", merged_df.shape)
display(merged_df.tail())
merged_df.dtypes.value_counts()
merged_df.dtypes
merged_df["tls_ssl_certificate"].value_counts()

Merged dataset shape: (1549360, 115)

,url,Label,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,...,qty_asterisk_fragment,qty_hashtag_fragment,qty_dollar_fragment,qty_percent_fragment,fragment_length,time_response,qty_redirects,http_status,server_header,tls_ssl_certificate
1549355,http://jdmtube.com,False,1,0,0,2,0,0,0,0,...,0,0,0,0,0,-1.0,0,-1.0,NaN,0
1549356,http://naaleads.com,False,1,0,0,2,0,0,0,0,...,0,0,0,0,0,1695.0,1,301.0,CloudFront,0
1549357,http://viagra25.us,False,1,0,0,2,0,0,0,0,...,0,0,0,0,0,336.0,1,301.0,cloudflare,0
1549358,http://gortenziya.shop,False,1,0,0,2,0,0,0,0,...,0,0,0,0,0,737.0,1,301.0,nginx-reuseport/1.21.1,0
1549359,http://karatsc.ru,False,1,0,0,2,0,0,0,0,...,0,0,0,0,0,754.0,1,301.0,nginx/1.26.3,0

tls_ssl_certificate
0    1549351
1          9
Name: count, dtype: int64

In [ ]:
from google.colab import files

# Save the merged dataframe to a CSV file
merged_df.to_csv("final_features.csv", index=False)

# Provide a download link for the CSV file
files.download("final_features.csv")

**Dataset rebuild**

In [ ]:
import pandas as pd

# Load the phishing dataset
df_phishing = pd.read_csv("phishing_site_urls.csv")

# Map labels in phishing dataset: bad -> 1 (phishing), good -> 0 (legit)
df_phishing['Label'] = df_phishing['Label'].map({'bad': 1, 'good': 0})

# Load Tranco dataset (no header)
tranco_df = pd.read_csv("tranco_7NZNX.csv", header=None, names=["Rank", "Domain"])

# Create full URLs by prefixing http://
tranco_df["URL"] = "http://" + tranco_df["Domain"]

# Assign label = 0 (benign) to Tranco dataset
tranco_df["Label"] = 0

# Keep only relevant columns from Tranco dataset
benign_df = tranco_df[["URL", "Label"]]

# Concatenate the dataframes
merged_df = pd.concat([df_phishing, benign_df], ignore_index=True)

# Display the first few rows of the merged dataframe and its shape
print("Merged dataset shape:", merged_df.shape)
display(merged_df.head())

Merged dataset shape: (1549360, 2)

                                                 URL  Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...    1.0
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...    1.0
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....    1.0
3  mail.printakid.com/www.online.americanexpress....    1.0
4  thewhiskeydregs.com/wp-content/themes/widescre...    1.0

In [ ]:
from google.colab import files

# Save the merged dataframe to a CSV file
merged_df.to_csv("merged_dataset.csv", index=False)

# Provide a download link for the CSV file
files.download("merged_dataset.csv")